=== Talentica/HungryHippos/configuration-schema/src/main/resources/schema/client-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.talentica.com/hungryhippos/config/client"
	xmlns:tns="http://www.talentica.com/hungryhippos/config/client"
	elementFormDefault="qualified">

	<element name="client-config">
		<complexType>
			<sequence>
				<element type="tns:coordination-servers" name="coordination-servers"
					nillable="false" />
				<element name="session-timout" type="string" default="86400000" />
				<element type="tns:output" name="output" />
				<element type="boolean" name="data-file-sorting"  default="false"/>
			</sequence>
		</complexType>
	</element>

	<complexType name="coordination-servers">
		<sequence>
			<element type="string" name="servers" maxOccurs="1"
				minOccurs="1" />
		</sequence>
	</complexType>
	
	<complexType name="output">
		<sequence>
			<element type="string" name="node-ssh-username" />
			<element type="string" name="node-ssh-private-key-file-path" />
		</sequence>
	</complexType>
</schema>

=== Talentica/HungryHippos/configuration-schema/src/main/resources/schema/client-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<<<<<<< Updated upstream
<tns:client-config xmlns:tns="http://www.talentica.com/hungryhippos/config/client" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.talentica.com/hungryhippos/config/client client-config.xsd ">
  <tns:coordination-servers>
    <tns:servers>localhost:2181</tns:servers>
  </tns:coordination-servers>
  <tns:session-timout>86400000</tns:session-timout>
  <tns:output>
    <tns:node-ssh-username>tns:node-ssh-username</tns:node-ssh-username>
    <tns:node-ssh-private-key-file-path>tns:node-ssh-private-key-file-path</tns:node-ssh-private-key-file-path>
  </tns:output>
=======
<tns:client-config xmlns:tns="http://www.talentica.com/hungryhippos/config/client"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.talentica.com/hungryhippos/config/client client-config.xsd ">
	<tns:coordination-servers>
		<tns:servers>localhost:2181</tns:servers>
	</tns:coordination-servers>
	<tns:session-timout>86400000</tns:session-timout>
	<tns:output>
		<tns:node-ssh-username>tns:node-ssh-username</tns:node-ssh-username>
		<tns:node-ssh-private-key-file-path>tns:node-ssh-private-key-file-path</tns:node-ssh-private-key-file-path>
	</tns:output>
>>>>>>> Stashed changes
</tns:client-config>
