=== Talentica/HungryHippos/configuration-schema/src/main/resources/schema/cluster-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.talentica.com/hungryhippos/config/cluster"
	xmlns:tns="http://www.talentica.com/hungryhippos/config/cluster"
	elementFormDefault="qualified">
	<element name="cluster-config">
		<complexType>
			<sequence>
				<element type="tns:node" name="node" maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>

	<complexType name="node">
		<sequence>
			<element type="int" name="identifier" />
			<element type="string" name="name" />
			<element type="string" name="ip" />
			<element type="string" name="port" />
		</sequence>
	</complexType>

</schema>

=== Talentica/HungryHippos/configuration-schema/src/main/resources/distribution/cluster-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:cluster-config
	xmlns:tns="http://www.talentica.com/hungryhippos/config/cluster"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.talentica.com/hungryhippos/config/cluster cluster-config.xsd ">
	<tns:node>
		<tns:identifier>0</tns:identifier>
		<tns:name>node0</tns:name>
		<tns:ip>138.68.24.131</tns:ip>
		<tns:port>2324</tns:port>
	</tns:node>
	<tns:node>
		<tns:identifier>1</tns:identifier>
		<tns:name>node1</tns:name>
		<tns:ip>138.68.26.162</tns:ip>
		<tns:port>2324</tns:port>
	</tns:node>
	<tns:node>
		<tns:identifier>2</tns:identifier>
		<tns:name>node2</tns:name>
		<tns:ip>138.68.22.5</tns:ip>
		<tns:port>2324</tns:port>
	</tns:node>
	<tns:node>
		<tns:identifier>3</tns:identifier>
		<tns:name>node3</tns:name>
		<tns:ip>138.68.22.71</tns:ip>
		<tns:port>2324</tns:port>
	</tns:node>
	<tns:node>
		<tns:identifier>4</tns:identifier>
		<tns:name>node4</tns:name>
		<tns:ip>138.68.25.8</tns:ip>
		<tns:port>2324</tns:port>
	</tns:node>
</tns:cluster-config>
