=== Talentica/HungryHippos/configuration-schema/src/main/resources/schema/filesystem-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.talentica.com/hungryhippos/config/filesystem"
	xmlns:tns="http://www.talentica.com/hungryhippos/config/filesystem"
	elementFormDefault="qualified">
	<element name="file-system-config">
		<complexType>
			<sequence>
				<element type="string" name="root-directory"></element>
				<element type="string" name="data-file-prefix"></element>
				<element type="int" name="server-port"></element>
				<element type="long" name="query-retry-interval"></element>
				<element type="int" name="max-query-attempts"></element>
				<element type="int" name="file-stream-buffer-size"></element>
				<element type="int" name="max-client-requests"></element>
			</sequence>
		</complexType>

	</element>
</schema>

=== Talentica/HungryHippos/hhspark_automation/distr_original/config/filesystem-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:file-system-config xmlns:tns="http://www.talentica.com/hungryhippos/config/filesystem" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.talentica.com/hungryhippos/config/filesystem filesystem-config.xsd ">
  <tns:root-directory>/home/hhuser/hh/filesystem</tns:root-directory>
	<tns:data-file-prefix>data_</tns:data-file-prefix>
	<tns:append-to-data-file>false</tns:append-to-data-file>
	<tns:server-port>9898</tns:server-port>
	<tns:query-retry-interval>2500</tns:query-retry-interval>
	<tns:max-query-attempts>10</tns:max-query-attempts>
	<tns:file-stream-buffer-size>2048</tns:file-stream-buffer-size>
	<tns:max-client-requests>25</tns:max-client-requests>
</tns:file-system-config>

=== Talentica/HungryHippos/configuration-schema/src/main/resources/schema/filesystem-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:file-system-config xmlns:tns="http://www.talentica.com/hungryhippos/filesystem"
                        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                        xsi:schemaLocation="http://www.talentica.com/hungryhippos/filesystem filesystem-config.xsd ">
    <tns:root-directory>/tmp/hungryhippo_root</tns:root-directory>
    <tns:data-file-prefix>data_</tns:data-file-prefix>
    <tns:server-port>9898</tns:server-port>
    <tns:query-retry-interval>2500</tns:query-retry-interval>
    <tns:max-query-attempts>10</tns:max-query-attempts>
    <tns:file-stream-buffer-size>2048</tns:file-stream-buffer-size>
    <tns:max-client-requests>25</tns:max-client-requests>
</tns:file-system-config>
