=== Talentica/HungryHippos/configuration-schema/src/main/resources/schema/job-runner-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.talentica.com/hungryhippos/config/jobrunner"
	xmlns:tns="http://www.talentica.com/hungryhippos/config/jobrunner"
	elementFormDefault="qualified">
	<element name="job-runner-config">
		<complexType>
			<sequence>
				<element type="long" name="no-of-rows-to-check-available-memory" />
				<element type="long" name="min-free-memory-in-mbs" />
				<element type="long" name="no-of-rows-to-check-memory-consumption-after" />
				<element type="long" name="no-of-rows-to-log-progress-after" />
				<element type="int"
					name="max-no-of-gc-retries-when-single-valueset-is-in-process" />
				<element type="long"
					name="wait-time-in-ms-after-gc-is-requested-for-single-valueset-is-in-process" />
				<element type="string" name="jar-root-directory" />
			</sequence>
		</complexType>
	</element>

</schema>

=== Talentica/HungryHippos/coordination/src/test/resources/config/job-runner-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright [2017] [Talentica Software Pvt. Ltd.]
   
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
   
        http://www.apache.org/licenses/LICENSE-2.0
   
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
 -->

<tns:job-runner-config
        xmlns:tns="http://www.talentica.com/hungryhippos/config/jobrunner"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.talentica.com/hungryhippos/config/jobrunner job-runner-config.xsd ">
        <tns:no-of-rows-to-check-available-memory>2000</tns:no-of-rows-to-check-available-memory>
        <tns:min-free-memory-in-mbs>100</tns:min-free-memory-in-mbs>
        <tns:no-of-rows-to-check-memory-consumption-after>1000</tns:no-of-rows-to-check-memory-consumption-after>
        <tns:no-of-rows-to-log-progress-after>3000000</tns:no-of-rows-to-log-progress-after>
        <tns:max-no-of-gc-retries-when-single-valueset-is-in-process>5</tns:max-no-of-gc-retries-when-single-valueset-is-in-process>
        <tns:wait-time-in-ms-after-gc-is-requested-for-single-valueset-is-in-process>
                5000</tns:wait-time-in-ms-after-gc-is-requested-for-single-valueset-is-in-process>
        <tns:jobs-root-directory>/home/sudarshans/hh/JobJars</tns:jobs-root-directory>
</tns:job-runner-config>
