=== Talentica/HungryHippos/configuration-schema/src/main/resources/schema/sharding-client-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.talentica.com/hungryhippos/sharding/client"
	xmlns:tns="http://www.talentica.com/hungryhippos/sharding/client"
	elementFormDefault="qualified">
	<element name="sharding-client-config">
		<complexType>
			<sequence>
				<element type="tns:input" name="input" />
				<element type="tns:output" name="output" />
				<element type="tns:bad-records-output" name="bad-records-output" />
				<element type="tns:sharding-dimensions" name="sharding-dimensions" />
				<element type="int" name="maximum-size-of-single-block-data" />
			</sequence>
		</complexType>
	</element>

	<complexType name="output">
		<sequence>
			<element type="string" name="output-dir"></element>
		</sequence>
	</complexType>

	<complexType name="input">
		<sequence>
			<element type="string" name="sample-file-path" />
			<element type="tns:data-description" minOccurs="0"
				name="data-description" />
			<element type="tns:data-parser-config" name="data-parser-config" />
		</sequence>
	</complexType>
	
	<complexType name="bad-records-output">
		<sequence>
			<element type="string" name="bad-records-file-out"/>
		</sequence>
	</complexType>
	
	<complexType name="data-parser-config">
		<sequence>
			<element type="string" name="class-name" />
			<element type="string" name="jar-file-path" />
		</sequence>
	</complexType>

	<complexType name="data-description">
		<sequence>
			<element type="tns:column" name="column" maxOccurs="unbounded"></element>
		</sequence>
	</complexType>

	<complexType name="column">
		<sequence>
			<element name="name" type="string" />
			<element name="description" minOccurs="0" type="string" />
			<element name="data-type">
				<simpleType>
					<restriction base="string">
						<enumeration value="STRING"></enumeration>
						<enumeration value="INT"></enumeration>
						<enumeration value="FLOAT"></enumeration>
						<enumeration value="DOUBLE"></enumeration>
						<enumeration value="LONG"></enumeration>
					</restriction>
				</simpleType>
			</element>
			<element name="size" minOccurs="0" type="int" default="0" />
		</sequence>
	</complexType>
	
	<complexType name="sharding-dimensions">
		<sequence>
			<element name="sharding-dimension-keys" type="string"/>
			<element name="keys-prefix" type="string"/>
		</sequence>
	</complexType>

</schema>

=== Talentica/HungryHippos/coordination/src/test/resources/config/sharding-client-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:sharding-client-config
	xmlns:tns="http://www.talentica.com/hungryhippos/config/sharding"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.talentica.com/hungryhippos/config/sharding sharding-client-config.xsd ">
	<tns:input>
<tns:sample-file-path>/home/sudarshans/data_spark_char.csv</tns:sample-file-path>
<tns:distributed-file-path>/sudarshans/100lines</tns:distributed-file-path>
		<tns:data-description>
			<tns:column>
				<tns:name>key1</tns:name>
				<tns:data-type>STRING</tns:data-type>
				<tns:size>1</tns:size>
			</tns:column>
			<tns:column>
				<tns:name>key2</tns:name>
				<tns:data-type>LONG</tns:data-type>
				<tns:size>0</tns:size>
			</tns:column>
			
		</tns:data-description>
		<tns:data-parser-config>
			<tns:class-name>com.talentica.hungryHippos.client.data.parser.CsvDataParser</tns:class-name>
<tns:jar-file-path>/root/hungryhippos_chefsolo_vagrant_modularise/test-jobs.jar</tns:jar-file-path>
		</tns:data-parser-config>
	</tns:input>
	<tns:sharding-dimensions>key1</tns:sharding-dimensions>
	<tns:maximum-size-of-single-block-data>80</tns:maximum-size-of-single-block-data>
  <tns:bad-records-file-out>/home/sudarshans/bad_rec.err</tns:bad-records-file-out>
  <tns:data-file-sorting>true</tns:data-file-sorting>
</tns:sharding-client-config>

=== Talentica/HungryHippos/configuration-schema/src/main/resources/distribution/sharding-client-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:sharding-client-config
	xmlns:tns="http://www.talentica.com/hungryhippos/config/sharding"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.talentica.com/hungryhippos/config/sharding sharding-client-config.xsd ">
	<tns:input>
		<tns:sample-file-path>/home/pooshans/HungryHippos/HungryHippos/utility/sampledata.csv</tns:sample-file-path>
		<tns:distributed-file-path>/pooshan/dir/input</tns:distributed-file-path>
		<tns:data-description>
			<tns:column>
				<tns:name>key1</tns:name>
				<tns:data-type>STRING</tns:data-type>
				<tns:size>1</tns:size>
			</tns:column>
			<tns:column>
				<tns:name>key2</tns:name>
				<tns:data-type>STRING</tns:data-type>
				<tns:size>1</tns:size>
			</tns:column>
			<tns:column>
				<tns:name>key3</tns:name>
				<tns:data-type>STRING</tns:data-type>
				<tns:size>1</tns:size>
			</tns:column>
			<tns:column>
				<tns:name>key4</tns:name>
				<tns:data-type>STRING</tns:data-type>
				<tns:size>3</tns:size>
			</tns:column>
			<tns:column>
				<tns:name>key5</tns:name>
				<tns:data-type>STRING</tns:data-type>
				<tns:size>3</tns:size>
			</tns:column>
			<tns:column>
				<tns:name>key6</tns:name>
				<tns:data-type>STRING</tns:data-type>
				<tns:size>3</tns:size>
			</tns:column>
			<tns:column>
				<tns:name>key7</tns:name>
				<tns:data-type>DOUBLE</tns:data-type>
				<tns:size>0</tns:size>
			</tns:column>
			<tns:column>
				<tns:name>key8</tns:name>
				<tns:data-type>DOUBLE</tns:data-type>
				<tns:size>0</tns:size>
			</tns:column>
			<tns:column>
				<tns:name>key9</tns:name>
				<tns:data-type>STRING</tns:data-type>
				<tns:size>5</tns:size>
			</tns:column>
		</tns:data-description>
		<tns:data-parser-config>
			<tns:class-name>com.talentica.hungryHippos.client.data.parser.CsvDataParser</tns:class-name>
			<tns:jar-file-path>/home/pooshans/HungryHippos/HungryHippos/test-hungry-hippos/build/libs/test-jobs.jar</tns:jar-file-path>
		</tns:data-parser-config>
	</tns:input>
	<tns:sharding-dimensions>key1,key2,key3</tns:sharding-dimensions>
	<tns:maximum-size-of-single-block-data>80</tns:maximum-size-of-single-block-data>
</tns:sharding-client-config>
